* Construcción de una red neuronal para la **clasificación de tipos de flores**.

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

## Carga de datos

In [7]:
###################################################
# 1. Load data
###################################################
datos = pd.read_csv('/home/walter/Documents/serie-notas/z_data/datos_curso_redes_neuronales/Iris.csv')
datos.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [13]:
###################################################
# 2. Preprocessing
###################################################
target = 'class'
features = ['sepallength', 'sepalwidth','petallength','petalwidth']

X = datos[features]
y = datos[target]

# Encoding de target, para responder al problema de 3 categorías
encoder = LabelEncoder()
y_cat = encoder.fit_transform(y)
y_cat = to_categorical(y_cat)

# separación train-test
X_train, X_test, y_train, y_test=train_test_split(X, y_cat, test_size=0.20)

# normalizo tanto los datos  X de entrenamiento como los de testeo
normalizador = StandardScaler()
X_train = normalizador.fit_transform(X_train)
X_test = normalizador.transform(X_test)
X_train[0:5]

array([[-0.89831615,  1.6874758 , -1.22385162, -1.14556954],
       [-1.02039763,  0.53430327, -1.27975653, -1.27787786],
       [-0.04374586,  2.14874481, -1.39156635, -1.27787786],
       [-1.26456057,  0.07303426, -1.16794671, -1.27787786],
       [-1.50872351,  0.07303426, -1.22385162, -1.27787786]])

In [18]:
###################################################
# 3. Design NN
###################################################
# 1. Número de neuronas en capa de entrada: 4 (una por feature)
# 2. Número de neuronas en capa de salida: 3 (una por categoría)
# 3. Capas ocultas: 1
# 4. Nro neuronas en capa oculta : 1
# 5. Función de activación de la capa oculta: tanh
# 6. Función de activación capa output: sigmoide
# 7. Algoritmo: SGD (descenso del gradiente estocástico)
# 8. Función de error: MSE
# 9. Medida de perfomance: ACCURACY

# parámetros
nIn = X_train.shape[1] # 1 per feature
nOut = y_train.shape[1] # 3 values for response
ocultas = 1

# diseño
model = Sequential()
model.add(Dense(ocultas, input_shape=[nIn], activation='tanh'))
model.add(Dense(nOut, activation='sigmoid'))
model.summary()  #-- muestra la cantidad de parámetros de la red
model.compile(optimizer=SGD(lr=0.1), loss='mse', metrics='accuracy')
#-- se utilizará SGD (descenso de gradiente estocástico),
#-- MSE (error cuadrático medio) y ACCURACY como medida de performance

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 1)                 5         
                                                                 
 dense_7 (Dense)             (None, 3)                 6         
                                                                 
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________


In [19]:
###################################################
# 4. Train
###################################################
model.fit(X_train, y_train, epochs=100, batch_size=20);

Epoch 1/100
6/6 [==============================] - 0s 867us/step - loss: 0.3343 - accuracy: 0.0167
Epoch 2/100
6/6 [==============================] - 0s 719us/step - loss: 0.3254 - accuracy: 0.0250
Epoch 3/100
6/6 [==============================] - 0s 919us/step - loss: 0.3166 - accuracy: 0.1917
Epoch 4/100
6/6 [==============================] - 0s 727us/step - loss: 0.3079 - accuracy: 0.2000
Epoch 5/100
6/6 [==============================] - 0s 941us/step - loss: 0.2994 - accuracy: 0.2250
Epoch 6/100
6/6 [==============================] - 0s 875us/step - loss: 0.2910 - accuracy: 0.2417
Epoch 7/100
6/6 [==============================] - 0s 1ms/step - loss: 0.2829 - accuracy: 0.2417
Epoch 8/100
6/6 [==============================] - 0s 780us/step - loss: 0.2749 - accuracy: 0.2667
Epoch 9/100
6/6 [==============================] - 0s 773us/step - loss: 0.2673 - accuracy: 0.2917
Epoch 10/100
6/6 [==============================] - 0s 878us/step - loss: 0.2600 - accuracy: 0.3083
Epoch 11/10

In [42]:
###################################################
# 4. Predict (in sample)
###################################################
y_pred = model.predict(X_train)
pd.concat([pd.DataFrame(y_pred), pd.DataFrame(y_train)], axis=1).head(20)

4/4 [==============================] - 0s 1ms/step


0         1         2    0    1    2
0   0.803124  0.177942  0.147425  1.0  0.0  0.0
1   0.799534  0.179415  0.149063  1.0  0.0  0.0
2   0.803795  0.177666  0.147119  1.0  0.0  0.0
3   0.792994  0.182070  0.152027  1.0  0.0  0.0
4   0.794901  0.181299  0.151165  1.0  0.0  0.0
5   0.114873  0.500771  0.556681  0.0  0.0  1.0
6   0.113177  0.502637  0.559062  0.0  0.0  1.0
7   0.228201  0.410202  0.438860  0.0  1.0  0.0
8   0.118202  0.497175  0.552087  0.0  0.0  1.0
9   0.113915  0.501821  0.558021  0.0  0.0  1.0
10  0.116831  0.498645  0.553966  0.0  1.0  0.0
11  0.798391  0.179881  0.149583  1.0  0.0  0.0
12  0.118008  0.497382  0.552352  0.0  0.0  1.0
13  0.798888  0.179678  0.149357  1.0  0.0  0.0
14  0.145936  0.470221  0.517374  0.0  1.0  0.0
15  0.143789  0.472142  0.519862  0.0  1.0  0.0
16  0.122256  0.492913  0.546630  0.0  1.0  0.0
17  0.115638  0.499936  0.555616  0.0  0.0  1.0
18  0.116109  0.499425  0.554963  0.0  0.0  1.0
19  0.132972  0.482212  0.532873  0.0  0.0  1.0

In [43]:
Y_pred_nro = np.argmax(y_pred,axis=1)  #-- conversión a entero
Y_true = np.argmax(y_train,axis=1)
print("%% aciertos X_train : %.3f" % accuracy_score(Y_true, Y_pred_nro))
report = classification_report(Y_true, Y_pred_nro)

% aciertos X_train : 0.683


/home/walter/.virtualenvs/gen_env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/walter/.virtualenvs/gen_env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/walter/.virtualenvs/gen_env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)

In [44]:
print("Confusion matrix TRAIN:\n%s" % report)
cm = confusion_matrix(Y_true, Y_pred_nro)
print("Confusion matrix:\n%s" % cm) 


Confusion matrix TRAIN:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        43
           1       0.00      0.00      0.00        38
           2       0.51      1.00      0.67        39

    accuracy                           0.68       120
   macro avg       0.50      0.67      0.56       120
weighted avg       0.52      0.68      0.58       120

Confusion matrix:
[[43  0  0]
 [ 0  0 38]
 [ 0  0 39]]


In [45]:
#--- TESTEO ---
Y_pred = model.predict(X_test)
Y_pred_nro = np.argmax(Y_pred,axis=1)  #-- conversión a entero

Y_true = np.argmax(y_test,axis=1)
print("%% aciertos X_test : %.3f" % accuracy_score(Y_true, Y_pred_nro))
report = classification_report(Y_true, Y_pred_nro)

print("Confusion matrix TEST:\n%s" % report)
cm = confusion_matrix(Y_true, Y_pred_nro)
print("Confusion matrix:\n%s" % cm) 

1/1 [==============================] - 0s 13ms/step
% aciertos X_test : 0.600
Confusion matrix TEST:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       0.00      0.00      0.00        12
           2       0.48      1.00      0.65        11

    accuracy                           0.60        30
   macro avg       0.49      0.67      0.55        30
weighted avg       0.41      0.60      0.47        30

Confusion matrix:
[[ 7  0  0]
 [ 0  0 12]
 [ 0  0 11]]


/home/walter/.virtualenvs/gen_env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/walter/.virtualenvs/gen_env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/walter/.virtualenvs/gen_env/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)